base_url=https://pre-prod.cartup.com
admin_base_url=https://pre-prod-admin.cartup.com
inventory_base_url=https://pre-prod-inventory.cartup.com/
slow_mo=0
proxy=false
proxy_url=http://localhost:8080
login_mobile=01627557563
login_password=123456

base_url_seller=https://pre-prod-partner-v2.cartup.com/
seller_login_mobile=01627557563
seller_login_password=Bd@19711
admin_username=sqaadmin
admin_password=Bd@#2025
Cs_base_url=https://pre-prod-cs.cartup.com/
CS_userName=zakaria_shahed
CS_password=Bd@19711

base_url_logistics=https://pre-prod-logistics.cartup.com
login_user_logistics=logisticsadminsqa
login_password_logistics=Bd@_1971
login_sort_user_logistics=sort_user
login_sort_password_logistics=Bd@_1971

inventory_username=admin
inventory_password=Cart@123up

base_url_accounting=https://pre-prod-accounting.cartup.com
login_user_accounting=admin
login_password_accounting=Cart@123up
